# Generated by Django 5.2.7 on 2025-10-14 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='season',
        ),
        migrations.RemoveField(
            model_name='team',
            name='sport',
        ),
        migrations.AddField(
            model_name='team',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='team',
            name='max_players_allowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='CoachProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Basketball', 'Basketball'), ('Football', 'Football'), ('Soccer', 'Soccer'), ('Baseball', 'Baseball'), ('Volleyball', 'Volleyball'), ('Track & Field', 'Track & Field'), ('Tennis', 'Tennis'), ('Swimming', 'Swimming'), ('Other', 'Other')], max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
