# Generated by Django 5.2.7 on 2025-10-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_remove_team_season_remove_team_sport_team_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sport',
            field=models.CharField(default='', max_length=100),
        ),
    ]
