# Generated by Django 5.2.8 on 2025-12-04 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('opponent', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField()),
                ('is_win', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_pt_made', models.IntegerField(default=0)),
                ('two_pt_att', models.IntegerField(default=0)),
                ('three_pt_made', models.IntegerField(default=0)),
                ('three_pt_att', models.IntegerField(default=0)),
                ('ft_made', models.IntegerField(default=0)),
                ('ft_att', models.IntegerField(default=0)),
                ('rebound_off', models.IntegerField(default=0)),
                ('rebound_def', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('steals', models.IntegerField(default=0)),
                ('blocks', models.IntegerField(default=0)),
                ('turnovers', models.IntegerField(default=0)),
                ('fouls', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='coach.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='coach.player')),
            ],
            options={
                'unique_together': {('game', 'player')},
            },
        ),
    ]
