# Generated by Django 5.2.8 on 2025-12-04 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_game_playerstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='coach.event'),
        ),
    ]
