# Generated by Django 5.2.8 on 2025-11-17 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_add_missing_player_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coach.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
