# Generated by Django 5.2.8 on 2025-11-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_coachprofile_gender_player_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachprofile',
            name='gender',
            field=models.CharField(blank=True, default='Not specified', max_length=20),
        ),
    ]
