# Generated by Django 5.2.8 on 2025-11-18 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_player_created_at'),
        ('coach', '0008_profile'),
    ]

    operations = [
    ]
