# Generated by Django 5.2.8 on 2025-11-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0010_event_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachprofile',
            name='gender',
        ),
        migrations.AddField(
            model_name='coachprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
