# Generated by Django 5.2.8 on 2025-11-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_remove_coachprofile_gender_coachprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
    ]
